### ISSUE TITLE
getLogFC returns primerid that is just a sequence of numbers instead of the primerid in zlm object

### ISSUE THREAD

**Issue by myajima** [RGLab/SingleCellAssay#51]
Calling getLogFC on zlm object returns data table object that does not have primerid of the original zlm object.  The column primerid is just a sequence of numbers.  logFC retains the ordering of the genes.
```
#example
> a<-getLogFC(zlm_cond_sh)
> b<-logFC(zlm_cond_sh)
> 
> stopifnot(all(a$primerid==rownames(b[[1]])))
Error: all(a$primerid == rownames(b[[1]])) is not TRUE
> stopifnot(all(fData(zlm_cond_sh@sca)$primerid==rownames(b[[1]])))
> stopifnot(all(fData(zlm_cond_sh@sca)$primerid==a$primerid))
Error: all(fData(zlm_cond_sh@sca)$primerid == a$primerid) is not TRUE

```

**Comment by gfinak** [comment]
There's a few issues here. 
1. The order of getLogFC doesn't match the order of the genes as you claim. In fact the lengths are different as getLogFC returns multiple rows for each gene depending on how many contrasts are requested. The order of getLogFC is by primerid, not the order in the sca object. 
2. The primerids are coerced to numeric values if they are characters initially. This is clearly a bug.
 
Whether or not the order of getLogFC should match the sca object, I'm not sure, but I don't see why it should. In general, you're getting a data table so it should be easy to subset the genes you're interested in. The only problem is the different types (numeric vs character).

**Comment by gfinak** [comment]
Reproducible example with code that we all have access to:
```
library(SCRAMDataPackage)
library(parallel)
data(SCRAMDataPackage)
options(mc.cores=7)
fit<-zlm.SingleCellAssay(sca=sca_monocle,~Media+cngeneson,parallel=TRUE)
a<-getLogFC(fit)
b<-logFC(fit)
all(a$primerid==rownames(b[[1]]))
[1] FALSE
all(fData(fit@sca)$primerid==rownames(b[[1]]))
[1] TRUE
all(fData(fit@sca)$primerid==a$primerid)
[1] FALSE
nrow(fData(fit@sca))
[1] 11890
nrow(b[1])
[1] 11890
nrow(a)
23780
```

Fix is to make the call to `getLogFC` cast primerid to a character (which it is in `fData`), and set the order as it appears in `fData`, as follows:
```
getLogFC <- function(zlmfit, contrast0, contrast1){
    lfc <- logFC(zlmfit, contrast0, contrast1)
    logFC <- dcast.data.table(data.table(melt(lfc)), primerid + contrast ~ L1)
    logFC[,primerid:=as.character(primerid)] #cast to character
    logFC[,z:=logFC/sqrt(varLogFC)]
    setkey(logFC,primerid) #key on primerid
    logFC=logFC[dimnames(lfc[[1]])$primerid,] #order by primerid as in fData
    logFC
}
```
